name: ci
on:
  workflow_dispatch
jobs:
  build_monorepo:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: build
          nxCloud: 'true'